Update modify-icons.yml

diff --git a/.github/workflows/modify-icons.yml b/.github/workflows/modify-icons.yml
--- a/.github/workflows/modify-icons.yml
+++ b/.github/workflows/modify-icons.yml
@@ -1,25 +1,25 @@
 name: Modify Icons
 
 on:
-  workflow_run:
-    workflows: ["Sync Upstream Icons"]
-    types:
-      - completed
+  workflow_dispatch:
 
 jobs:
   process:
     runs-on: ubuntu-latest
-
+    outputs:
+      upload_url: ${{ steps.create_or_update_release.outputs.upload_url }}
+      version: ${{ steps.fetch_tag.outputs.latest_tag }}
+      
     steps:
       # Step 1: Checkout Fork Repo
       - name: Checkout Fork Repo
-        uses: actions/checkout@v3
+        uses: actions/checkout@v4
         with:
           fetch-depth: 0
 
       # Step 2: Set up Node.js environment
       - name: Set up Node.js
-        uses: actions/setup-node@v3
+        uses: actions/setup-node@v4
         with:
           node-version: '20'
 
@@ -77,19 +77,20 @@ jobs:
           LATEST_TAG=$(git ls-remote --tags https://github.com/tabler/tabler-icons.git | \
           grep -o 'refs/tags/.*' | sed 's/refs\/tags\///' | sort -V | tail -n1)
           echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV
+          echo "::set-output name=latest_tag::$LATEST_TAG"
 
       # Step 10: Create or Update GitHub Release
       - name: Create or Update GitHub Release
         id: create_or_update_release
         run: |
-          TAG_NAME="${{ env.LATEST_TAG }}"
+          TAG_NAME="${{ steps.fetch_tag.outputs.latest_tag }}"
           RELEASE_NAME="Kustom Tabler Icons - $TAG_NAME"
           API_URL="https://api.github.com/repos/${{ github.repository }}/releases"
           
           # Check if release with tag already exists
           RELEASE_ID=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" $API_URL | \
           jq -r ".[] | select(.tag_name == \"$TAG_NAME\") | .id")
-
+          
           if [ -z "$RELEASE_ID" ]; then
             # Create a new release if it doesn't exist
             RESPONSE=$(curl -s -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
@@ -97,6 +98,7 @@ jobs:
             -d '{"tag_name": "'"$TAG_NAME"'","name": "'"$RELEASE_NAME"'","draft": false,"prerelease": false}' \
             $API_URL)
             UPLOAD_URL=$(echo "$RESPONSE" | jq -r ".upload_url" | sed 's/{?name,label}//')
+            echo "::set-output name=upload_url::$UPLOAD_URL"
           else
             # Update the existing release if it does
             RESPONSE=$(curl -s -X PATCH -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
@@ -104,13 +106,24 @@ jobs:
             -d '{"name": "'"$RELEASE_NAME"'"}' \
             "$API_URL/$RELEASE_ID")
             UPLOAD_URL=$(echo "$RESPONSE" | jq -r ".upload_url" | sed 's/{?name,label}//')
+            echo "::set-output name=upload_url::$UPLOAD_URL"
           fi
 
-      # Step 11: Upload zip file to the release
+  upload:
+    runs-on: ubuntu-latest
+    needs: process
+    steps:
+      - name: Check File Existence
+        run: |
+          if [ ! -f ./kustom-tabler-icons.zip ]; then
+            echo "File not found!"
+            exit 1
+          fi
+
       - name: Upload Release Asset
         uses: actions/upload-release-asset@v1
         with:
-          upload_url: ${{ env.UPLOAD_URL }}
+          upload_url: ${{ needs.process.outputs.upload_url }}
           asset_path: ./kustom-tabler-icons.zip
           asset_name: kustom-tabler-icons.zip
           asset_content_type: application/zip
